### PR TITLE
Fix edit Legal Bug

### LINKED ISSUE #254: [Bug Report]: change legal requires to change title
### Description

If I only want to change the text of the legal document I still need to change legal Title

### Steps to reproduce the Bug

click on edit Legal button
try to change text without changing the title

### Comment

_No response_

### PR DESCRIPTION
**Pull request by FinnKeller**
Now you can change the name/text however you want and it will be displayed correctly on the site itself and in the dialog. fixes #254

### CODE REVIEW

File: app/pages/legal/[slug].vue [hunk 1]
```diff
@@ -9,17 +9,37 @@ definePageMeta({
...
+const openForm = (event: boolean) => {
+  open.value = event
+  if (event) {
+    form.resetForm()
+  }
+}
+
+watch (() => legal.value, (newLegal) => {
+  if (!open.value) {
+    form.resetForm({
```
Comment (niklhut) [inline app/pages/legal/[slug].vue:34]: Maybe rather use form.setValues instead of form.resetForm

**Review by niklhut — CHANGES_REQUESTED** [review]

**Review by niklhut — APPROVED** [review]
